- name: Download and install yadm binary
  ansible.builtin.get_url:
    url: https://github.com/TheLocehiliosan/yadm/raw/master/yadm
    dest: /usr/local/bin/yadm
    mode: "0777"
  become: yes

- name: Yadm clone
  ansible.builtin.command:
    cmd: "yadm clone {{ dotfiles_url_https }}"

- name: change yadm remote url
  ansible.builtin.command:
    cmd: "yadm remote set-url origin {{ dotfiles_url_ssh }}"
