- name: Enable copr in Fedora distro
  community.general.copr:
    host: copr.fedorainfracloud.org
    name: agriffis/neovim-nightly
    state: enabled
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Add neovim ppa in ubuntu
  ansible.builtin.command:
    argv:
      - sudo
      - add-apt-repository
      - ppa:neovim-ppa/unstable
      - -y
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Apt-get update
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install or update neovim
  ansible.builtin.package:
    name: neovim
    state: latest
  become: yes
  tags:
    - install

- name: Clone packer.nvim to neovim packpath
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    repo: https://github.com/wbthomason/packer.nvim

- name: Clone the nvim dotfiles
  ansible.builtin.git:
    clone: yes
    dest: "{{ ansible_user_dir }}/.config/nvim"
    repo: https://github.com/rifqoi/nvim

- name: run :PackerSync
  ansible.builtin.command:
    cmd: nvim -u ~/.config/nvim/lua/packer_nvim.lua --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
